
import "./globals.css";
import Footer from "../components/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "react-hot-toast";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
